import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: "PushpaSamriddhi",
    appTagline: "Floriculture Knowledge for Every Farmer",
    home: "Home",
    articles: "Articles",
    marketplace: "Marketplace",
    askExpert: "Ask Expert",
    profile: "Profile",
    settings: "Settings",
    search: "Search...",
    searchPlaceholder: "Search flowers, articles, prices...",
    cultivation: "Cultivation",
    pestManagement: "Pest & Disease",
    govSchemes: "Govt Schemes",
    marketPrices: "Market Prices",
    weather: "Weather",
    news: "News",
    featuredArticles: "Featured Articles",
    trendingPrices: "Trending Prices",
    quickActions: "Quick Actions",
    viewAll: "View All",
    buy: "Buy",
    sell: "Sell",
    postListing: "Post Listing",
    myListings: "My Listings",
    allListings: "All Listings",
    price: "Price",
    perKg: "per kg",
    contact: "Contact",
    readMore: "Read More",
    send: "Send",
    typeMessage: "Type your message...",
    askAnything: "Ask anything about flower farming...",
    temperature: "Temperature",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    rainfall: "Rainfall",
    farmingSuggestion: "Farming Suggestion",
    organicFarming: "Organic Farming",
    seasonalTips: "Seasonal Tips",
    diseasePrevention: "Disease Prevention",
    flowerType: "Flower Type",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    loading: "Loading...",
    noResults: "No results found",
    language: "Language",
    logout: "Logout",
    login: "Login",
    register: "Register",
    welcomeBack: "Welcome Back",
    helpContact: "Help & Contact",
    dailyNews: "Daily News",
    chatWithAI: "Chat with AI Expert",
    uploadImage: "Upload Image",
    quantity: "Quantity",
    location: "Location",
    active: "Active",
    sold: "Sold",
    cancelled: "Cancelled",
    forgotPassword: "Forgot Password",
  },
  hi: {
    appName: "पुष्पसमृद्धि",
    appTagline: "हर किसान के लिए फूलों की खेती का ज्ञान",
    home: "होम",
    articles: "लेख",
    marketplace: "बाज़ार",
    askExpert: "विशेषज्ञ से पूछें",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    search: "खोजें...",
    searchPlaceholder: "फूल, लेख, कीमतें खोजें...",
    cultivation: "खेती",
    pestManagement: "कीट प्रबंधन",
    govSchemes: "सरकारी योजनाएं",
    marketPrices: "बाज़ार भाव",
    weather: "मौसम",
    news: "समाचार",
    featuredArticles: "विशेष लेख",
    trendingPrices: "ट्रेंडिंग कीमतें",
    quickActions: "त्वरित कार्य",
    viewAll: "सभी देखें",
    buy: "खरीदें",
    sell: "बेचें",
    postListing: "विज्ञापन डालें",
    myListings: "मेरे विज्ञापन",
    allListings: "सभी विज्ञापन",
    price: "कीमत",
    perKg: "प्रति किलो",
    contact: "संपर्क",
    readMore: "और पढ़ें",
    send: "भेजें",
    typeMessage: "अपना संदेश लिखें...",
    askAnything: "फूलों की खेती के बारे में कुछ भी पूछें...",
    temperature: "तापमान",
    humidity: "नमी",
    windSpeed: "हवा की गति",
    rainfall: "बारिश",
    farmingSuggestion: "खेती सुझाव",
    organicFarming: "जैविक खेती",
    seasonalTips: "मौसमी सुझाव",
    diseasePrevention: "रोग निवारण",
    flowerType: "फूल का प्रकार",
    cancel: "रद्द करें",
    save: "सहेजें",
    edit: "संपादन",
    delete: "हटाएं",
    loading: "लोड हो रहा है...",
    noResults: "कोई परिणाम नहीं मिला",
    language: "भाषा",
    logout: "लॉग आउट",
    login: "लॉग इन",
    register: "रजिस्टर",
    welcomeBack: "वापस स्वागत है",
    helpContact: "सहायता और संपर्क",
    dailyNews: "दैनिक समाचार",
    chatWithAI: "AI विशेषज्ञ से बात करें",
    uploadImage: "फोटो अपलोड करें",
    quantity: "मात्रा",
    location: "स्थान",
    active: "सक्रिय",
    sold: "बिका",
    cancelled: "रद्द",
    forgotPassword: "पासवर्ड भूल गए",
  },
  kn: {
    appName: "ಪುಷ್ಪಸಮೃದ್ಧಿ",
    appTagline: "ಪ್ರತಿ ರೈತರಿಗೆ ಹೂವಿನ ಕೃಷಿ ಜ್ಞಾನ",
    home: "ಮುಖಪುಟ",
    articles: "ಲೇಖನಗಳು",
    marketplace: "ಮಾರುಕಟ್ಟೆ",
    askExpert: "ತಜ್ಞರನ್ನು ಕೇಳಿ",
    profile: "ಪ್ರೊಫೈಲ್",
    settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
    search: "ಹುಡುಕಿ...",
    searchPlaceholder: "ಹೂವುಗಳು, ಲೇಖನಗಳು, ಬೆಲೆಗಳನ್ನು ಹುಡುಕಿ...",
    cultivation: "ಕೃಷಿ",
    pestManagement: "ಕೀಟ ನಿರ್ವಹಣೆ",
    govSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    marketPrices: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು",
    weather: "ಹವಾಮಾನ",
    news: "ಸುದ್ದಿ",
    featuredArticles: "ವಿಶೇಷ ಲೇಖನಗಳು",
    trendingPrices: "ಟ್ರೆಂಡಿಂಗ್ ಬೆಲೆಗಳು",
    quickActions: "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
    viewAll: "ಎಲ್ಲಾ ನೋಡಿ",
    buy: "ಖರೀದಿ",
    sell: "ಮಾರಾಟ",
    postListing: "ಪೋಸ್ಟ್",
    readMore: "ಇನ್ನಷ್ಟು ಓದಿ",
    send: "ಕಳುಹಿಸಿ",
    typeMessage: "ನಿಮ್ಮ ಸಂದೇಶ ಬರೆಯಿರಿ...",
    temperature: "ತಾಪಮಾನ",
    humidity: "ತೇವಾಂಶ",
    windSpeed: "ಗಾಳಿ ವೇಗ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    language: "ಭಾಷೆ",
    logout: "ಲಾಗ್ ಔಟ್",
    login: "ಲಾಗ್ ಇನ್",
    chatWithAI: "AI ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್",
    dailyNews: "ದೈನಿಕ ಸುದ್ದಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    save: "ಉಳಿಸಿ",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ",
  },
  ta: {
    appName: "புஷ்பசம்ருத்தி",
    appTagline: "ஒவ்வொரு விவசாயிக்கும் மலர் வளர்ப்பு அறிவு",
    home: "முகப்பு",
    articles: "கட்டுரைகள்",
    marketplace: "சந்தை",
    askExpert: "நிபுணரிடம் கேளுங்கள்",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    search: "தேடு...",
    cultivation: "விவசாயம்",
    pestManagement: "பூச்சி மேலாண்மை",
    govSchemes: "அரசு திட்டங்கள்",
    marketPrices: "சந்தை விலை",
    weather: "வானிலை",
    news: "செய்திகள்",
    viewAll: "அனைத்தையும் காண",
    buy: "வாங்கு",
    sell: "விற்பனை",
    send: "அனுப்பு",
    loading: "ஏற்றுகிறது...",
    language: "மொழி",
    logout: "வெளியேறு",
    login: "உள்நுழை",
    chatWithAI: "AI நிபுணரிடம் பேசுங்கள்",
    cancel: "ரத்துசெய்",
    save: "சேமி",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா",
  },
  mr: {
    appName: "पुष्पसमृद्धी",
    appTagline: "प्रत्येक शेतकऱ्यासाठी फुलशेती ज्ञान",
    home: "मुखपृष्ठ",
    articles: "लेख",
    marketplace: "बाजार",
    askExpert: "तज्ञांना विचारा",
    profile: "प्रोफाइल",
    settings: "सेटिंग्ज",
    search: "शोधा...",
    cultivation: "शेती",
    pestManagement: "कीटक व्यवस्थापन",
    govSchemes: "सरकारी योजना",
    marketPrices: "बाजार भाव",
    weather: "हवामान",
    news: "बातम्या",
    viewAll: "सर्व पहा",
    buy: "खरेदी",
    sell: "विक्री",
    send: "पाठवा",
    loading: "लोड होत आहे...",
    language: "भाषा",
    logout: "लॉग आउट",
    login: "लॉग इन",
    chatWithAI: "AI तज्ञांशी बोला",
    cancel: "रद्द करा",
    save: "जतन करा",
    forgotPassword: "पासवर्ड विसरलात",
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('pushpa_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('pushpa_lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const languageOptions = [
    { code: 'en', label: 'English', nativeLabel: 'English' },
    { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
    { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
    { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
    { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  ];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languageOptions }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}